export const ACCOUNTING_TEXT = {
  vi: {
    systemError: "Lỗi hệ thống",
    requiredEmployeeCodeError: "Mã nhân viên không được để trống!",
    requiredFullNameError: "Tên không được để trống!",
    requiredDepartmentError: "Phòng ban không được để trống!",
    duplicatedEmployeeCodeError: "Mã nhân viên đã tồn tại!",
    deleteWarningText: "Bạn có thực sự muốn xóa Nhân viên {id} không?",
    deleteManyEmployeeWarning:
      "Bạn có thực sự muốn xóa các nhân viên đã chọn không?",
    successToast: {
      addEmployee: "Thêm nhân viên thành công!",
      updateEmployee: "Cập nhật nhân viên thành công!",
      deleteEmployee: "Xóa nhân viên thành công!",
      icon: "../../assets/icon/check-circle-solid.svg",
    },
    errorToast: {
      addEmployee: "Thêm nhân viên không thành công",
      updateEmployee: "Cập nhật nhân viên không thành công",
      deleteEmployee: "Xóa nhân viên thất bại!",
      icon: "../../assets/icon/circle-xmark-solid.svg",
    },
    warningToast: {
      icon: "../../assets/icon/check-circle-solid.svg",
    },
    warningDialog: {
      changeText: "Dữ liệu đã thay đổi. Bạn có muốn cất?",
    },
    words: {
      employee: "Nhân viên",
      yes: "Có",
      no: "Không",
      total: "Tổng",
      record: "bản ghi",
      recordPerPage: "bản ghi trên một trang",
      selected: "Đã chọn",
      deselect: "Bỏ chọn",
      selectAll: "Chọn tất cả",
      delete: "Xóa",
      add: "Thêm",
      removeFilters: "Xóa điều kiện lọc",
      searchByCodeAndName: "Tìm theo mã, tên nhân viên",
      refetchData: "Lấy lại dữ liệu",
      exportExcel: "Xuất ra excel",
      modifyDisplaySettings: "Tùy chỉnh giao diện",
      stopUsing: "Ngừng sử dụng",
      duplicate: "Nhân bản",
      warning: "Cảnh báo",
      inputSearchTerm: "Nhập từ khóa tìm kiếm",
      changeHeaderNameAndWidth: "Sửa tên cột hiển thị và độ rộng",
      headerName: "Tên cột dữ liệu",
      headerNameOnInterface: "Tên cột trên giao diện",
      width: "Độ rộng",
      fixColumn: "Cố định cột",
      fixThisColumn: "Cố định cột này",
      cancel: "Hủy",
      getDefaultTemplate: "Lấy mẫu ngầm định",
      store: "Cất",
      previous: "Trước",
      next: "Sau",
      filter: "Lọc",
      inputFilterValue: "Nhập giá trị lọc",
      male: "Nam",
      female: "Nữ",
      other: "Khác",
      unfilter: "Bỏ lọc",
      feature: "Chức năng",
      modify: "Sửa",
      storeAndAdd: "Cất và thêm",
      close: "Đóng",
      help: "Giúp",
      isEmployee: "Là nhân viên",
      isCustomer: "Là khách hàng",
    },
    operator: {
      isNull: "(Trống)",
      notNull: "(Không trống)",
      equal: "Bằng",
      notEqual: "Không bằng",
      contain: "Chứa",
      notContain: "Không chứa",
      startWith: "Bắt đầu với",
      endWith: "Kết thúc với",
    },
    headers: {
      employeeCode: "Mã nhân viên",
      fullName: "Tên nhân viên",
      genderName: "Giới tính",
      gender: "Giới tính",
      dateOfBirth: "Ngày sinh",
      identityNumber: "Số chứng minh nhân dân",
      identityDate: "Ngày cấp",
      identityPlace: "Nơi cấp",
      positionName: "Chức danh",
      departmentCode: "Mã đơn vị",
      departmentName: "Tên đơn vị",
      address: "Địa chỉ",
      phoneNumber: "ĐT di động",
      landline: "ĐT cố định",
      email: "Email",
    },
    form: {
      updateFormTitle: "Sửa thông tin nhân viên",
      createFormTitle: "Thêm thông tin nhân viên",
      employeeCode: {
        label: "Mã",
        placeholder: "Mã",
      },
      fullName: {
        label: "Tên",
        placeholder: "Họ và tên",
      },
      departmentName: {
        label: "Đơn vị",
        placeholder: "Đơn vị",
      },
      positionName: {
        label: "Chức danh",
        placeholder: "Chức danh",
      },
      dateOfBirth: {
        label: "Ngày sinh",
        placeholder: "Ngày sinh",
      },
      gender: {
        label: "Giới tính",
      },
      identityNumber: {
        label: "Số CMND",
        placeholder: "Số CMND",
        tooltipText: "Số chứng minh nhân dân",
      },
      identityDate: {
        label: "Ngày cấp",
        placeholder: "Ngày cấp",
      },
      identityPlace: {
        placeholder: "Nơi cấp",
        label: "Nơi cấp",
      },
      address: {
        label: "Địa chỉ",
        placeholder: "Địa chỉ",
      },
      phoneNumber: {
        label: "ĐT di động",
        placeholder: "Điện thoại di động",
        tooltipText: "Điện thoại cố định",
      },
      landline: {
        label: "ĐT cố định",
        placeholder: "Điện thoại cố định",
        tooltipText: "Điện thoại cố định",
      },
      email: {
        label: "Email",
        placeholder: "Email",
      },
      bankAccount: {
        label: "Tài khoản ngân hàng",
        placeholder: "Tài khoản ngân hàng",
      },
      bankName: {
        label: "Tên ngân hàng",
        placeholder: "Tên ngân hàng",
      },
      bankBranch: {
        label: "Chi nhánh",
        placeholder: "Chi nhánh",
      },
    },
  },
  en: {
    systemError: "System error",
    requiredEmployeeCodeError: "Employee code is required!",
    requiredFullNameError: "Fullname is required!",
    requiredDepartmentError: "Department is required!",
    duplicatedEmployeeCodeError: "Employee code is duplicated!",
    deleteWarningText: "Do you really want to delete Employee {id}?",
    deleteManyEmployeeWarning:
      "Do you really want to delete selected employees?",
    successToast: {
      addEmployee: "Add new employee successfully!",
      updateEmployee: "Update new employee successfully!",
      deleteEmployee: "Delete new employee successfully!",
      icon: "../../assets/icon/check-circle-solid.svg",
    },
    errorToast: {
      addEmployee: "Thêm nhân viên không thành công",
      updateEmployee: "Cập nhật nhân viên không thành công",
      deleteEmployee: "Xóa nhân viên thất bại!",
      icon: "../../assets/icon/circle-xmark-solid.svg",
    },
    warningToast: {
      icon: "../../assets/icon/check-circle-solid.svg",
    },
    warningDialog: {
      changeText: "Data has changed. Do you want to save?",
    },
    words: {
      employee: "Employee",
      yes: "Yes",
      no: "No",
      total: "Total",
      record: "record(s)",
      recordPerPage: "records per page",
      selected: "Select",
      deselect: "Deselect",
      selectAll: "Select all",
      delete: "Delete",
      add: "Add",
      removeFilters: "Remove all filters",
      searchByCodeAndName: "Search by code or name",
      refetchData: "Retrieve data",
      exportExcel: "Export to excel",
      modifyDisplaySettings: "Display options",
      stopUsing: "Cease using",
      duplicate: "Copy",
      warning: "Warning",
      inputSearchTerm: "Search",
      changeHeaderNameAndWidth: "Change column	&#8217;s name and width",
      headerName: "Column	&#8217;s name",
      headerNameOnInterface: "Displayed column	&#8217;s name",
      width: "Width",
      fixColumn: "Fix Column&#8217;s position",
      fixThisColumn: "Pin",
      cancel: "Cancel",
      getDefaultTemplate: "Use Default Template",
      store: "Save",
      previous: "Previous",
      next: "Next",
      filter: "Filter",
      inputFilterValue: "Enter value filter",
      male: "Male",
      female: "Female",
      other: "Other",
      unfilter: "Filter out",
      feature: "Function",
      modify: "Edit",
      storeAndAdd: "Save and Add",
      close: "Close",
      help: "Help",
      isEmployee: "Is Employee",
      isCustomer: "Is Customer",
    },
    operator: {
      isNull: "(Empty)",
      notNull: "(Filled)",
      equal: "Equal to",
      notEqual: "Not equal to",
      contain: "Contain",
      notContain: "Do not contain",
      startWith: "Start with",
      endWith: "End with",
    },
    headers: {
      employeeCode: "Subject ID",
      fullName: "Subject's name",
      genderName: "Gender",
      gender: "Gender",
      dateOfBirth: "Birth date",
      identityNumber: "Personal ID card No.",
      identityDate: "Issue date",
      identityPlace: "Issue by",
      positionName: "Position",
      departmentCode: "Unit ID",
      departmentName: "Unit's name",
      address: "Address",
      phoneNumber: "Contact mobilephone number",
      landline: "Phone number",
      email: "Email",
    },
    form: {
      updateFormTitle: "Edit employee information",
      createFormTitle: "Add employee information",
      employeeCode: {
        label: "ID",
        placeholder: "ID",
      },
      fullName: {
        label: "Name",
        placeholder: "Name",
      },
      departmentName: {
        label: "Unit",
        placeholder: "Unit",
      },
      positionName: {
        label: "Position",
        placeholder: "Position",
      },
      dateOfBirth: {
        label: "Date of birth",
        placeholder: "Date of birth",
      },
      gender: {
        label: "Gender",
      },
      identityNumber: {
        label: "Personal ID number",
        placeholder: "Personal ID number",
        tooltipText: "Personal ID number",
      },
      identityDate: {
        label: "Issue date",
        placeholder: "Issue date",
      },
      identityPlace: {
        placeholder: "Issue by",
        label: "Issue by",
      },
      address: {
        label: "Address",
        placeholder: "Address",
      },
      phoneNumber: {
        label: "Cellphone",
        placeholder: "Cellphone",
        tooltipText: "Cellphone",
      },
      landline: {
        label: "Landline",
        placeholder: "Landline",
        tooltipText: "Landline",
      },
      email: {
        label: "Email",
        placeholder: "Email",
      },
      bankAccount: {
        label: "Bank account",
        placeholder: "Bank account",
      },
      bankName: {
        label: "Bank name",
        placeholder: "Bank name",
      },
      bankBranch: {
        label: "Bank branch",
        placeholder: "Bank branch",
      },
    },
  },
};

export const ACCOUNTING_ENUM = {
  MODE: {
    ADD: 1,
    UPDATE: 2,
    DUPLICATE: 3,
  },
  DROPDOWN: {
    DEFAULT: 1,
    PAGINATION: 2,
    FORM: 3,
  },
  GENDER: {
    MALE: 1,
    FEMALE: 0,
    OTHER: 2,
  },
};
